steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'CACHEBUST=${_CACHEBUST}'
      - '-t'
      - '${_IMAGE}'
      - '.'
images:
  - '${_IMAGE}'
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/roundtable-public/roundtable/workspace:latest
  _CACHEBUST: '1'
